### ISSUE TITLE
The project does not compile

### ISSUE THREAD

**Issue by denruss** [gtortone/esp-xvcd#2]
sketch_apr21a:237:2: error: #endif without #if
 #endif
  ^
sketch_apr21a:239:2: error: #endif without #if
 #endif
  ^
exit status 1
#endif without #if

**Comment by denruss** [comment]
sketch_apr21a:231:13: error: expected ';' before 'client'
             client.print(MAX_WRITE_SIZE)
             ^
exit status 1
expected ';' before 'client'

**Comment by gtortone** [comment]
ok, try now... I merged a PR with some errors due to I did not test it...
